name: capstone_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  tflite_flutter: 0.10.3
  camera: ^0.10.0
  image: ^4.0.17
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  typed_data: ^1.3.0
  speech_to_text: 6.3.0
  flutter_tts: ^3.6.3
  http: ^1.3.0
  permission_handler: ^11.3.1
  uuid: ^4.1.0
  zego_uikit_prebuilt_call: ^4.16.28
  local_auth: ^2.1.6
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  firebase_auth_mocks: any
  fake_cloud_firestore: any
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/1_Dollar_Sample.png
    - assets/model/currency_model.tflite
